# Generated by Django 3.1.3 on 2021-05-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210504_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcreate',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
