# Generated by Django 3.1.3 on 2021-05-06 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210506_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcreate',
            name='discription',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
