# Generated by Django 3.1.3 on 2021-05-07 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0005_classcreate_discription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.TextField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='files')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auther', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.classcreate')),
            ],
        ),
    ]
