# Generated by Django 3.1.3 on 2021-05-08 12:06

import backend.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_addwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='addwork',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addwork',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=backend.models.upload_path),
        ),
    ]
