# Generated by Django 3.1.3 on 2021-05-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_submitedworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcreate',
            name='discription',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='submitedworks',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
