# Generated by Django 3.1.3 on 2021-05-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210517_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='addwork',
            name='submition',
            field=models.DateField(blank=True, null=True),
        ),
    ]
