# Generated by Django 3.1.3 on 2021-05-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_addwork_submition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addwork',
            name='submition',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
