# Generated by Django 3.1.3 on 2021-05-18 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0012_joinclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcreate',
            name='accessors',
            field=models.ManyToManyField(related_name='accessors', to=settings.AUTH_USER_MODEL),
        ),
    ]
