# Generated by Django 3.1.3 on 2021-05-18 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_classcreate_accessors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JoinClass',
        ),
    ]
