# Generated by Django 3.1.3 on 2021-05-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_delete_joinclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitedworks',
            name='Message',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
