# Generated by Django 3.1.3 on 2021-05-28 17:43

import datetimeutc.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20210521_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitedworks',
            name='created',
            field=datetimeutc.fields.DateTimeUTCField(auto_now_add=True),
        ),
    ]
