# Generated by Django 3.1.3 on 2021-06-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_submitedworks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitedworks',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
